### ISSUE TITLE
Will the ResDAVEnet code be released?

### ISSUE THREAD

**Issue by chwlsunny** [dharwath/DAVEnet-pytorch#3]
Hello harwath, I have conducted some experiments about the image-speech retrieval task on the basis of your released code, and I treat your methods(ECCV2018 and IJCV2020) as the baselines, but I have trouble in reproducing the ResDAVEnet model, will you plan to release the ResDAVEnet code recently?

**Comment by roudimit** [comment]
Hi, 

I'm not David (although I work with him), but I believe the model you are referring to is released here: https://github.com/wnhsu/ResDAVEnet-VQ

**Comment by chwlsunny** [comment]
> Hi,
> 
> I'm not David (although I work with him), but I believe the model you are referring to is released here: https://github.com/wnhsu/ResDAVEne

> Hi,
> 
> I'm not David (although I work with him), but I believe the model you are referring to is released here: https://github.com/wnhsu/ResDAVEnet-VQ

Hello roudimit, thank you very much for your prompt, and it does great help for me.
